[screen]
width = 800
height = 480
origin_x = 1920
origin_y = 1080

# Preset Configuration to run through
[preset]
pvp_tickets = 5
pvp_runs = 2
world_boss_difficulty = "Heroic"
world_boss_runs = 10
raid_difficulty = "Heroic"
raid_runs = 4
gvg_tickets = 0
gvg_runs = 0
invasion_tickets = 0
invasion_runs = 0
trials_tickets = 0
trials_runs = 0
guantlet_tickets = 0
guantlet_runs = 0


# Distance from top left corner in x and y
[positions]
quest = 0
pvp = 0
pvp_play = 0
pvp_fight = 0
world_boss = 0
world_boss_summon_1 = 0
world_boss_summon_2 = 0
world_boss_difficulty = 0
world_boos_normal = 0
world_boss_hard = 0
world_boss_heroic = 0
raid = 0
raid_summon = 0
raid_normal = 0
raid_heroic = 0
raid_hard = 0
gvg = 0
gvg_play = 0
invasion = 0
invasion_play = 0
trials = 0
trials_play = 0
guantlet = 0
guantlet_play = 0
