[screen]

width = 1920
height = 1080
origin = [560, 300]


# Preset Configuration to run through
[preset]

pvp_tickets = 5
pvp_runs = 2

world_boss_difficulty = "Heroic"
world_boss_runs = 10

raid_difficulty = "Heroic"
raid_runs = 4

gvg_tickets = 0
gvg_runs = 0

invasion_tickets = 0
invasion_runs = 0

trials_tickets = 0
trials_runs = 0

guantlet_tickets = 0
guantlet_runs = 0



# Distance from top left corner in x and y stored as a toml array
# Contains all the different buttons provided in the UI
[position]

quest = [35, 70]
quest_exit = [710, 100]

pvp = [35, 140]
pvp_play = [550, 290]
pvp_fight = [590, 200]
pvp_accept = [515, 455]
pvp_town = [490, 475]
pvp_exit = [635, 135]

world_boss = [35, 275]
world_boss_summon_1 = [500, 460]
world_boss_summon_2 = [545, 380]
world_boss_summon_3 = [475, 405]
world_boss_start = [385, 465]
world_boss_confirm = [340, 365]
world_boss_difficulty = [0, 0]
world_boss_normal = [0, 0]
world_boss_hard = [0, 0]
world_boss_heroic = [0, 0]
world_boss_town = [555, 470]
world_boss_exit = [655, 130]

raid = [35, 340]
raid_summon = [540, 375]
raid_normal = [225, 245]
raid_hard = [400, 245]
raid_heroic = [590, 245]
raid_accept = [510, 465]
raid_town = [485, 475]
raid_exit = [625, 135]

gvg = [765, 200]
gvg_play = [545, 290]
gvg_exit = [635, 145]

invasion = [765, 200]
invasion_play = [545, 290, 0]
invasion_exit = [0, 0]

trials = [765, 275]
trials_play = [545, 290]
traisl_exit = [635, 140]

gauntlet = [765, 265]
gauntlet_play = [545, 290]
gauntlet_exit = [0, 0]


[duration]
pvp = 15
world_boss = 10
raid = 480
gvg = 480
invasion = 480
trials = 300
gauntlet = 300